# Base configs
baseurl: "https://tejasvi4.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tejasvi Munge"
subtitle: "See the world through my eyes!"
author: "Tejasvi Munge"
header:
 title: "Photography"
 subtitle: "by Tejasvi Munge "
footer:
 name: "Hey there, my name is Tejasvi"
 bio: "Hi! I am Tejasvi. I am a business analyst and an enthusiastic amateur photographer from India. Love  and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
