# Base configs
baseurl: "https://tejasvi4.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tejasvi Munge"
subtitle: "See the world through my eyes!"
author: "Tejasvi Munge"
header:
 title: "Photography"
 subtitle: "by Tejasvi Munge "
footer:
 name: "Hey there, my name is Tejasvi"
 bio: "I am a business analyst and an enthusiastic amateur photographer from India."
 github: "https://github.com/tejasvi4"
web_design: "TM"
social_urls:
  instagram: "https://www.instagram.com/tejasvi___munge"
  linkedin: "https://in.linkedin.com/in/tejasvi-m-73a213145"
  github: "https://www.github.com/tejasvi4"
